### ISSUE TITLE
Word西文应用成功，中文应用失败

### ISSUE THREAD

**Issue by xiaodong-lu** [TrionesType/zhuque#11]
安装 0.107 版后，在Office 365 Word中应用，西文成功，中文失败，仍显示为 SimSun。怀疑与Windows 系统语言为英语有关？但其他字体无此问题，不知道是否需要额外做什么操作？

**Comment by xiaodong-lu** [comment]
没有解决。设置完 Asian text font 后，在字体设置对话框中 Preview 是正常的，但是点 OK 后，页面中的文字字体只显示为 SimSun。很奇怪。

**Comment by celestialphineas** [comment]
请您尝试重新下载 Releases 中的 v0.107（经过一次撤回重发，且与通过脚本构建的二进制可能会有所不同），清空字体缓存、重启电脑，试试看是否会有所帮助。

**Comment by xiaodong-lu** [comment]
好像还是不行。我又试了 v0.106，这次西文直接乱码，中文显示为微软雅黑。
可能是我电脑的某些设置不太对，感觉暂时要放弃了。
