### ISSUE TITLE
中文逗号不能显示。

### ISSUE THREAD

**Issue by RUANRui-ECON** [TrionesType/zhuque#12]
我用vscode+latexworkshop+xelatex，加载了朱雀字体，汉字都能正常显示，但是中文逗号和句号不能显示，英文逗号可以显示。
![image](https://github.com/TrionesType/zhuque/assets/12607066/21cc65b4-967d-4a6a-8c6b-59e21983b7d9)

**Comment by celestialphineas** [comment]
请您更新到 v0.107 看看呢？

**Comment by hushidong** [comment]
参考：https://github.com/TrionesType/zhuque/issues/4

**Comment by RUANRui-ECON** [comment]
试了，可以了，谢谢！


 
发件人： Celestial Phineas
发送时间： 2023-08-31 23:13
收件人： TrionesType/zhuque
抄送： RUANRui; Author
主题： Re: [TrionesType/zhuque] 中文逗号不能显示。 (Issue #12)
请您更新到 v0.107 看看呢？
