### ISSUE TITLE
好多豆腐

### ISSUE THREAD

**Issue by ArcCal** [TrionesType/zhuque#14]
<img width="701" alt="image" src="https://github.com/TrionesType/zhuque/assets/588329/f2e21fca-3f01-46d2-acd7-ce22b4e97d98">

**Comment by ArcCal** [comment]
不能正确显示书名号《》

**Comment by ArcCal** [comment]
<img width="689" alt="image" src="https://github.com/TrionesType/zhuque/assets/588329/2297611d-419c-451f-8187-0fa8c513f1e1">
<img width="672" alt="image" src="https://github.com/TrionesType/zhuque/assets/588329/3f79abf4-a08e-42be-b5cb-1e3eb6ec3957">

**Comment by ArcCal** [comment]
<img width="649" alt="image" src="https://github.com/TrionesType/zhuque/assets/588329/e563ee65-1b98-4780-8c2e-4848f9d4d472">
<img width="648" alt="image" src="https://github.com/TrionesType/zhuque/assets/588329/3084f95c-4897-4bf4-8d5b-b4e05f6f406e">

**Comment by ArcCal** [comment]
<img width="385" alt="image" src="https://github.com/TrionesType/zhuque/assets/588329/82477a26-7671-40cf-9981-a0a2f1a631ae">
<img width="396" alt="image" src="https://github.com/TrionesType/zhuque/assets/588329/b34e6cb1-f2ef-4127-a885-b851e3fe3a32">

**Comment by ArcCal** [comment]
<img width="527" alt="image" src="https://github.com/TrionesType/zhuque/assets/588329/fa0c7f60-58f9-49c2-b696-cc9c66c187ff">
<img width="562" alt="image" src="https://github.com/TrionesType/zhuque/assets/588329/e4826716-b83f-48fb-a486-d297a8eb5ad1">

**Comment by ArcCal** [comment]
<img width="551" alt="image" src="https://github.com/TrionesType/zhuque/assets/588329/128bc53f-959e-401b-b14d-6e7f759a5140">
<img width="531" alt="image" src="https://github.com/TrionesType/zhuque/assets/588329/9edfde50-df80-413e-aa48-4536edebcc2e">

**Comment by celestialphineas** [comment]
当前朱雀仿宋仍然处于测试版，并没有包含全部字形。请阅读发行说明，不要刷楼，缺字问题集中反馈到 #6 。您上面列举的问题也全都不必反馈，我们仍在设计中。
