### ISSUE TITLE
关于0.107的反馈和些许建议！

### ISSUE THREAD

**Issue by digiw** [TrionesType/zhuque#15]
很棒的字体，非常喜欢！
1. 如果朱雀能类似霞鹜文楷一样拥有多重字版本就好了！字体粗细胖瘦就可以自由选择了。
2. 使用字体制作软件导入安卓系统后，发现“采用 Alegreya 作为暂时的匹配西文” 这个方案不如0.106的西文方案来的舒适，在安卓系统下，这个西文字体会造成数字和英文字体略偏小，且显示颜色非常淡，读取困难。
3. 新版0.107和chrome浏览器似乎有兼容性问题，地址栏输入某些拼音后比如（jiang），候选框可选字展示不全，盲打可以输出！换其他浏览器没有这个问题，
![图像_2023-09-10_193830651](https://github.com/TrionesType/zhuque/assets/5784996/d1a49456-45ae-4f14-9b05-4930810de1ba)

**Comment by lxgw** [comment]
针对第一条：
1、是「多字重（zhòng）」，不是「多重（chóng）字」；
2、「霞鹜文楷」的多字重实际上是机械加粗减细而成的。

**Comment by digiw** [comment]
> 针对第一条： 1、是「多字重（zhòng）」，不是「多重（chóng）字」； 2、「霞鹜文楷」的多字重实际上是机械加粗减细而成的。

谢谢您的指正！
霞鹜的加粗方案，在手机上感觉挺好的！很感谢作者！话说回来现在移动端的字体选择也不多，厂家一般都只是在自己商店开放自有字库下载，仍旧挺封闭的！第三方字体得借助magisk才行，没有直达的方案，追求文字美的门槛真高。
例如我的安卓平板，暂时似乎还不能获取root，就只能看着第三方字体泪流满面...，读个kindle 被原生字体勒的难受，毕竟还是国人更了解中文字体的美。

**Comment by celestialphineas** [comment]
您好，感谢您的建议和反馈。

1. 我们目前有做三个字重的打算，但会在 v1.0 之后提上日程。
2. v0.106 版并没有包含西文字符，您在使用 v0.106 时看到的西文是缺字回退到的系统字体。当前匹配的 Alegreya 西文，其粗度灰度还是稍黑于朱雀汉字的。
3. 很难确定这是否是字体的问题，需要来自其他用户的复现信息。

**Comment by digiw** [comment]
> 您好，感谢您的建议和反馈。
> 
> 1. 我们目前有做三个字重的打算，但会在 v1.0 之后提上日程。
> 2. v0.106 版并没有包含西文字符，您在使用 v0.106 时看到的西文是缺字回退到的系统字体。当前匹配的 Alegreya 西文，其粗度灰度还是稍黑于朱雀汉字的。
> 3. 很难确定这是否是字体的问题，需要来自其他用户的复现信息。

感谢您的答复，对于第二点，确实0106版对于手机来说，手机启用的是原生字体的西文，因此看起来更加的清晰和醒目，在移动端，对西文的搭配方案还是很保持进一步期待的！
继续支持！！
