### ISSUE TITLE
刚刚发现，最新的v0.108不支持这些字符

### ISSUE THREAD

**Issue by ifp1090** [TrionesType/zhuque#18]
刚刚发现，最新的v0.108版本还不支持如下字符：
![image-20231018164041486](https://pbox.online/202310181640535.png)

**Comment by celestialphineas** [comment]
这些符号会在后续版本中补全。

**Comment by MY1L** [comment]
你发的截屏，不清楚是什么字符。该字体可能无法支持，也不需要支持➀~➉、➊~➓，原因在于——

❶：U+2776 DINGBAT NEGATIVE CIRCLED DIGIT ONE
➀：U+2780 DINGBAT CIRCLED **SANS-SERIF** DIGIT ONE
➊：U+278A DINGBAT NEGATIVE CIRCLED **SANS-SERIF** DIGIT ONE

❶与➊在无衬线字体里一般是没有区别的，但❶~❿没有规定字体。

但仿宋是“有”衬线字体，而➀~➉、➊~➓规定了是无衬线体（SANS-SERIF），因此仿宋体不需要支持这20字，就算支持，字面上也不对呀。
