### ISSUE TITLE
字体有问题。数字和英文都会显示为乱码

### ISSUE THREAD

**Issue by sandycs-protoss** [TrionesType/zhuque#2]
字体有问题。数字和英文都会显示为乱码

**Comment by celestialphineas** [comment]
试用版字体目前只覆盖《通用规范汉字表》一级与二级汉字，不包含西文与符号。在正式版发布之前，字体的设计与规格都可能发生很大改变。我们十分欢迎您填写 README 中的问卷，告诉我们您的想法。
