### ISSUE TITLE
破折号不连续

### ISSUE THREAD

**Issue by yisibl** [TrionesType/zhuque#22]
![image](https://github.com/TrionesType/zhuque/assets/2784308/6e0f6c69-9683-4acf-a233-1f7b52fd6cb6)

建议增加 twoemdash 字符 `U+2E3A`，通过 `ccmp` 的 OpenType feature 将两个 emdash 映射到 twoemdash

**Comment by yisibl** [comment]
![image](https://github.com/TrionesType/zhuque/assets/2784308/5e4da3a3-44be-4d23-92e2-1dfceeb6e013)
使用 locl 的方式感觉有点矫枉过正，依赖渲染端手动设置语言。

**Comment by celestialphineas** [comment]
> 2. `loclZHS` 的实现方式是权宜之计。后面我们会为 `U+2E3A TWO EM DASH` 做一个中文破折号字形，并用 `ccmp` 实现。省略号也会在后续版本中更新。

_Originally posted by @celestialphineas in https://github.com/TrionesType/zhuque/issues/19#issuecomment-1774650336_

**Comment by yisibl** [comment]
@celestialphineas 棒！

**Comment by celestialphineas** [comment]
间隔号 `· U+00B7` 的造型也需要更新。#23

**Comment by MY1L** [comment]
`locl`是必要的，不然中英文混排总有一方显得难看，我这边应急做了个带中文省略号的也是靠`locl`，可以试试：
https://github.com/TrionesType/zhuque/issues/24

我也有其它巧妙方法，如果你急用的话下次更新加上。

**Comment by celestialphineas** [comment]
@MY1L 这个问题璇玑团队会修正。目前我们在 CJK 上的优先级仍然在汉字，不在符号和排版特性上。`dev` 分支上的 CJK 部分后面会发生很大变动，请少安毋躁。

**Comment by celestialphineas** [comment]
[v0.211](https://github.com/TrionesType/zhuque/releases/tag/v0.211) 已修复。

* 对不支持 OpenType 特性的软件，破折号显示为顶框、连续
* 对支持 OpenType 特性的软件，破折号显示为不顶框、连续，利用上下文替代字 `calt` 实现
* 西文混排通过 `calt` 感知前一字符为大写字母还是小写字母实现，移除 `locl` 实现
