### ISSUE TITLE
外国人姓和名之间常用的"."无法显示

### ISSUE THREAD

**Issue by mrpengify** [TrionesType/zhuque#23]
显示错误
<img width="78" alt="d96e038faff6d1ef41a035359b76c71" src="https://github.com/TrionesType/zhuque/assets/29375336/0de04ab9-63aa-466a-a7c7-a2e693178df4">

同样的点在思源宋体中：
<img width="87" alt="8dc92afd3d7ba12941d31e89a8e9789" src="https://github.com/TrionesType/zhuque/assets/29375336/22c448a6-cec1-4e7a-8523-147658b74ac4">

在但凡是用到西方人姓名的地方，这个点的用处还挺频繁的，盼能补足，谢谢。

**Comment by lxgw** [comment]
· `U+00B7` 应该是有的

**Comment by celestialphineas** [comment]
该字符在最新版中已经加入，但造型还有问题，我们后续会改进。
