### ISSUE TITLE
Lack of Vertical Ellipsis Support

### ISSUE THREAD

**Issue by Honoka55** [TrionesType/zhuque#26]
The `vert` OpenType feature lacks vertical ellipsis support, causing horizontal rendering (`…`) in some vertical text contexts. While many modern applications and browsers handle this adequately, the inclusion of this feature is crucial for compatibility with older software. Please consider adding a vertical ellipsis glyph (`︙`) and mapping it in the OpenType feature. Thank you.

**Comment by celestialphineas** [comment]
Duplicated per #19 . We will take care of the ellipsis in the next version.
