### ISSUE TITLE
不妨添加31+1+4个希伯来仿宋（尤其是₪和ℵ）

### ISSUE THREAD

**Issue by MY1L** [TrionesType/zhuque#29]
最近偶然在一以色列字体网站上发现了这个“希伯来仿宋”，[Dragon.zip](https://github.com/TrionesType/zhuque/files/14667889/Dragon.zip)。其字体信息如下：
> Copyright (c) 2010, Printer Killer (<http://openfontlibrary.org/people/PrinterKiller>),
> - SIL Open Font License, Version 1.1 with Reserved Font Name MigdalHaemeq.

该字体尤其展示了“希伯来母语者眼中‘希伯来仿宋’可以是啥样的”，虽然字形质量不佳但可借鉴，也许AI处理后手工修饰为一致即可。

包含31个希伯来文+₪，并不全，但据 https://github.com/be5invis/Iosevka/issues/690 ，这些字对当地人而言够用，可以不需要特性，
> To the best of my understanding it doesn't have any complex typesetting rules. While it's true that Hebrew can optionally have diacritic marks which complicate things, the basic glyphs have no such requirement, and most day-to-day uses of Hebrew can get by just fine without them.

![image](https://github.com/TrionesType/zhuque/assets/58043328/7a41c6c8-15da-4134-a54c-4437df7709cd)

至少位于类字符号区段的4个[Left-to-Right]属性希伯来符号“ℵℶℷℸ”可添加，这些符号较为常用，例如B站有大量视频以[ℵ](https://search.bilibili.com/all?keyword=%E2%84%B5)为标题。

**Comment by celestialphineas** [comment]
非常感谢您宝贵的意见，是很实际的需求。关于其他文种匹配问题，朱雀项目有一定的立场与考量。

《方寸之间：汉字文字设计文集》一书，《浅谈多文种字体设计在全球化背景下的需求和方法》一文提及：

> 匹配字体……一定希望每一个文种的字体都能传递出相似的情感。虽然用相似的书写工具、相似的笔画特征进行匹配设计是一种比较稳妥的方案，但有时单纯地贴合原字体的造型，未必能传递出与原字体相同的情感主张。

朱雀的情感主张是「含蓄秀美」「书卷气」，这是我们在做多文种匹配工作所着重考虑的一点。除却功能与生态位在对应文种相似外，我们也希望对应文种风格在其文化中所能触发的情感是相似的。这是我们在触及其他文种时所希望保持的原则，即便是 Letterlike Symbols，最好也谨慎一些。

希望您能理解我们的一些考量，再次感谢您对朱雀项目的支持。
