### ISSUE TITLE
希望可以对古诗文中简化字做适配

### ISSUE THREAD

**Issue by Goosople** [TrionesType/zhuque#3]
现在我国大陆初高中语文教材对古诗文中许多字采用简化字，如“重湖叠巘清嘉”的“巘”采用“𪩘”（山献），“摐金伐鼓下榆关”的“摐”采用（扌从 U+2AB62），但大部分字体都不包含这些字（我目前没有找到包含U+2AB62的字体），因此大部分出版物（似乎也包括课本）以图片（有很多看起来像是位图）代之，给排版和阅读都带来了很多不便。如果你们的字体能包含这些简化字，或者用OpenType字体特性实现适配，鄙人感激不尽。（不过这个要求好像有点小众）

**Comment by celestialphineas** [comment]
如果您有更多需要的字，欢迎在这个 Issue 下面提出。我们的计划字表会参考的。

**Comment by celestialphineas** [comment]
整合至 #7
