### ISSUE TITLE
我希望能够做一个像是Adobe的思源黑体一样覆盖大部分的亚洲字体的字库,当字体的范围更大 就会有更强的生命力

### ISSUE THREAD

**Issue by jingyuexing** [TrionesType/zhuque#5]

**Comment by celestialphineas** [comment]
当然，那会是我们的长期计划，或是说理想。但是即便有新技术加持，做到这一步的成本也非常高昂。要知道思源黑体是 Adobe、Google 牵头，又有华文、Sandoll 等字体大厂参与，耗费多年才推出的产品。而我们只是一个三人的字体设计团队。因此我们也在征集大家的想法，希望能让项目更可持续地发展下去。您可以填写[【此问卷】](https://www.wjx.cn/vm/QQgadJY.aspx)告诉我们您的想法。
